baseURL: "/"
title: "S. Praevis"
languageCode: "en"
theme: "PaperMod"
pagination:
  pagerSize: 10
enableRobotsTXT: true

outputs:
  home: [HTML, RSS]

taxonomies:
  tag: tags

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Blog
          url: /posts/
          weight: 10
        - name: Forecasts
          url: /forecasts/
          weight: 20
        - name: About
          url: /about/
          weight: 30
        - name: Contact
          url: /about/#contact
          weight: 40
  ru:
    languageName: Русский
    weight: 2
    menu:
      main:
        - name: Блог
          url: /posts/
          weight: 10
        - name: Прогнозы
          url: /forecasts/
          weight: 20
        - name: О проекте
          url: /about/
          weight: 30
        - name: Контакты
          url: /about/#контакты
          weight: 40

menu: {}

params:
  defaultTheme: dark
  disableThemeToggle: true
  ShowReadingTime: false
  assets:
    disableHLJS: true
  socialIcons:
    - name: email
      url: "mailto:spraevis@gmail.com"
    - name: twitter
      url: "https://x.com/spraevis"
    - name: telegram
      url: "https://t.me/spraevis"
    - name: github
      url: "https://github.com/spraevis"
